version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: meubanco_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    networks:
      - minha_rede_personalizada
    volumes:
      - mongodb_dados:/data/db

  mysql:
    image: mysql:8.0
    container_name: meubanco_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_atividade
    ports:
      - "3306:3306"
    networks:
      - minha_rede_personalizada
    volumes:
      - mysql_dados:/var/lib/mysql

networks:
  minha_rede_personalizada:
    driver: bridge

volumes:
  mongodb_dados:
  mysql_dados:
